AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function that handles a Slack slash command and echoes the details
  back to the user.
Resources:
  lunchborg:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: s3://lunchborg/sources/3241b861970bb00476fb0d452fab0f22
      Description: A function that handles a Slack slash command and echoes the details
        back to the user.
      MemorySize: 128
      Timeout: 10
      Role: arn:aws:iam::478262784215:role/Lunchborg
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /lunchborg/command
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /lunchborg
            Method: ANY
      Environment:
        Variables:
          LUNCHBORG_BUCKET: lunchborg
          SLACK_SIGNIN_SECRET: 77c979f5362caeb37669dfde35f8db8e
