---
swagger: "2.0"
info:
  version: "2019-06-08T18:55:24Z"
  title: "Lunchborg"
basePath: "/"
schemes:
- "https"
paths:
  /lunchborg/command:
    post:
      x-amazon-apigateway-integration:
        httpMethod: post
        type: aws
        requestTemplates:
          application/json: |
          {
              "headers": {
              #foreach($param in $input.params().header.keySet())
              "$param": "$util.escapeJavaScript($input.params().header.get($param))"
              #if($foreach.hasNext),#end
              #end
          }, 
    
          "body" : $input.json("$")
  
        }
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
